spring:
  # rabbitmq
  rabbitmq:
    host: 120.79.27.209
    username: root
    password: ENC(N6Q1PFu/R9XSs9XSL47ATg==)
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  # qq mail
  mail:
    host: smtp.qq.com
    username: 691409320@qq.com
    password:
#    host: smtp.sendgrid.net
#    username: apikey
#    password: ENC(5LqJgyN59KWGpKowyX3kMcx7MJtBKb+055adCF0H6/vConVPsArsQmQQmckdOW7h5nI4EXQmpta1u47oJJQhBYcQF3IBiU3Y7kfUG80yUiE=)
    default-encoding: utf-8
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.starttls.enabl: true
  # thymeleaf
  thymeleaf:
    cache: false
  redis:
    #redis数据库，默认是0
    database: 0
    #redis服务器地址
    host: 120.79.27.209
    #redis服务端口，默认6379
    port: 6379
    #redis密码，默认为空
    password: ENC(f9h/Sri/1QbNLl9EaFsBIg==)
# +++++++++++++++++++++++ 配置send grid +++++++++++++++++++++++
sendgrid:
  from:
    name: chet
    email: yuan691409320@gmail.com
  api-key: ENC(5LqJgyN59KWGpKowyX3kMcx7MJtBKb+055adCF0H6/vConVPsArsQmQQmckdOW7h5nI4EXQmpta1u47oJJQhBYcQF3IBiU3Y7kfUG80yUiE=)
